apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-product
  template:
    metadata:
      labels:
        app: service-product
    spec:
      containers:
        - name: service-product
          image: ghcr.io/cloud2scape/service-product:latest
          ports:
            - containerPort: 8663
