apiVersion: v1
kind: Service
metadata:
  name: service-account
spec:
  type: NodePort
  selector:
    app: service-account
  ports:
  - protocol: TCP
    port: 8661
    targetPort: 8661
    nodePort: 32001