apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-gateway
  labels:
    app: core-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-gateway
  template:
    metadata:
      labels:
        app: core-gateway
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: core-gateway
          image: ghcr.io/cloud2scape/core-gateway:latest
          #image: docker.io/laigasus/core-gateway:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: config-gateway