apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-order
  template:
    metadata:
      labels:
        app: service-order
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: service-order
          image: ghcr.io/cloud2scape/service-order:latest
          #image: docker.io/laigasus/service-order:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: config-order