apiVersion: v1
kind: Service
metadata:
  name: service-order
spec:
  type: NodePort
  selector:
    app: service-order
  ports:
  - protocol: TCP
    port: 8662
    targetPort: 8662
    nodePort: 32002