spring:
  application:
    name: core-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: service-account
            uri: lb://service-account
            predicates:
              - Path=/account/***
          - id: service-order
            uri: lb://service-order
            predicates:
              - Path=/order/***
          - id: service-product
            uri: lb://service-product
            predicates:
              - Path=/product/***

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: sesac