spring:
  application:
    name: core-gateway
  config:
    import:
      - "optional:classpath:/config/cloud.yml"
      - "optional:classpath:/config/database.yml"
      - "optional:classpath:/config/session.yml"

  profiles:
    active: ${PROFILE:dev}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
      ejb:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

okta:
  oauth2:
    issuer: https://${AUTH0_DOMAIN}/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}
    audience: https://${AUTH0_DOMAIN}/userinfo